ControllExpenses/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from expenses.views import TodoList
from account.views import LogIn

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^user/',include('account.urls')),
    re_path(r'^expenses/',include('expenses.urls')),
    re_path(r'^report',include('reports.urls')),
    re_path(r'^api/',include('expenses.api_url')),
    re_path('',LogIn)
]

account/urls.py
from django.urls import re_path
from account import views
app_name='accounts'
'''
    TODO: add class base views, and add urls to it.
    - add templates, add authentication and authorization
'''
urlpatterns = [
    re_path(r'singup', views.CreateUser,name='sign_up'),
    re_path(r'login', views.LogIn,name='log_in'),
    re_path(r'logout',views.LogOut, name="log_out")
]

expenses/urls.py
from django.urls import re_path
from expenses import views

app_name='expenses'
urlpatterns = [
    re_path(r'category/add/$', views.AddCategory.as_view(), name='add_category'), 
    re_path(r'category/$', views.CategoryListView.as_view(), name='category'),
    re_path(r'add/$', views.AddEntryAPI.as_view(), name="add"),
    # re_path(r'add/$', views.AddEntry.as_view(), name="add"),
    # re_path(r'user/(?P<user>\d+)/$', views.PersonData.as_view(), name='person_expenses'),
    re_path(r'user/', views.PersonData.as_view(), name='person_expenses'),
    re_path(r'income/',views.AddIncome.as_view(), name='add_income'),
    re_path(r'report/', views.Summary.as_view(), name='report'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Personal Expenses</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css\base.css' %}">
  {% block header %}
  {% endblock %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body style="height: 100%;">
  {% if user.is_authenticated %}
  <div class="new">
    <div class="left">
      <div class="left_symbol">
        H
      </div>
      <div class="left_option">
        <div class="left_option_item">
          <a href="{% url 'expenses:report' %}">Summary</a>
        </div>
        <div class="left_option_item">
          <a href="{% url 'expenses:person_expenses' %}">Entry</a>
        </div>
        <div class="left_option_item">
          <a href="{% url 'expenses:category' %}">Categories</a>
        </div>
      </div>
      <div class="left_logout">
        <a href="{% url 'accounts:log_out' %}">
          Log Out
        </a>
      </div>
    </div>
    <div class="content" style="background-color: #f5f6fa;">
      {% endif %}
      {% block body %}
      {% endblock %}
    </div>
  </div>
</body>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Personal Expenses</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css\login.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
      <div class="left">
      </div>
      <div class="right">
        <h2>Expenses Control</h2>
        <h3>Please either sign_up or log in to be able to use this app</h3>
        <div class="button">
          <div type="submit">
            <a href="{% url 'accounts:sign_up' %}">singup</a>
          </div>
          <div type="submit">
            <a href="{% url 'accounts:log_in' %}">Log in</a>
          </div>
        </div>
      </div>
    </div>
</body>
<script src="https://kit.fontawesome.com/954dce0394.js" crossorigin="anonymous"></script>

</html>

templates/person_expenses.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'css\login.css' %}">
{% endblock %}
{% block body %}
<div class="login">
  <div class="login_left">
    <div class="options">
      <h3>Log Out succesfull</h3>
      <h3>We hope to see you soon !</h3>
    </div>
    <div class="container">
      <span type="submit"><a href="{% url 'accounts:sign_up' %}">singup</a></span>
      <span type="submit"><a href="{% url 'accounts:log_in' %}">Log in</a> </span>
    </div>
  </div>
  <div class="login_right">
  </div>
</div>
{% endblock %}